### ISSUE TITLE
cách sử dụng

### ISSUE THREAD

**Issue by BanhMi939** [systemsiteseason/Decima_Engine_Font_Convert#1]
Chào bác, sau khi mình build tool thì chạy bằng cmd ko có dấu hiệu gì cả là sao v bác?

**Comment by systemsiteseason** [comment]
Usage:
Decima_Engine_Font_Convert.exe "G:\path\to\core\file" lấy font ufo
Decima_Engine_Font_Convert.exe "G:\path\to\folder\ufo" ""G:\path\to\core\file\origin" tạo file core mới
Đây chưa phải bản mới nhất. Bản mới nhất chưa đc push lên

**Comment by BanhMi939** [comment]
![image](https://user-images.githubusercontent.com/106416065/180639863-d916c7c4-7910-42af-9bb9-718301186172.png)
Mình type đúng rồi mà nó vẫn ko chạy gì hết mà hiện như khi mở cmd lên thôi ấy.

**Comment by systemsiteseason** [comment]
Game j ấy nhỉ?

**Comment by systemsiteseason** [comment]
Bạn có thể cung cấp file binary không?

**Comment by systemsiteseason** [comment]
Hiện tại chỉ mới test 2 game hoziron zero dawn và death stranding còn until down và horizon forbidden west chưa có file binary để xem.

**Comment by BanhMi939** [comment]
Mình làm font của hoziron zero dawn bản ps4 ấy, đây bác. https://easyupload.io/fsqwl9

**Comment by systemsiteseason** [comment]
đã support

**Comment by BanhMi939** [comment]
> đã support

cám ơn bác nhiều.
